[package]
cargo-toml-patch-comments = [
    "default to the OpenSSL crypto backend of sequoia-openpgp",
]
extra-files = [
    "%{_libdir}/librpm_sequoia.so.1",
]
package-extra = """
%package     -n %{crate}-devel
Summary:        %{summary}
Requires:       %{crate}%{?_isa} = %{version}-%{release}

%description -n %{crate}-devel %{_description}

%files       -n %{crate}-devel
%{_libdir}/librpm_sequoia.so
%{_libdir}/pkgconfig/rpm-sequoia.pc
"""

suppress-cdylib-install-fixme = true

[scripts]
build.pre = [
    "# build script uses environment variables to populate the pkgconfig file",
    "export PREFIX=\"%{_prefix}\"",
    "export LIBDIR=\"%{_libdir}\"",
]
install.post = [
    "# install shared library",
    "mkdir -p %{buildroot}/%{_libdir}",
    "cp -pav target/release/librpm_sequoia.so %{buildroot}/%{_libdir}/librpm_sequoia.so.1",
    "# create unversioned symlink",
    "ln -s librpm_sequoia.so.1 %{buildroot}/%{_libdir}/librpm_sequoia.so",
    "# install pkg-config file",
    "mkdir -p %{buildroot}/%{_libdir}/pkgconfig",
    "cp -pav target/release/rpm-sequoia.pc %{buildroot}/%{_libdir}/pkgconfig/",
]
check.pre = [
    "# skip building library again in test code",
    "export TEST_DONT_BUILD_LIB=1",
]

