---
workflow:
  rules:
    # merge requests
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' &&
        $CI_MERGE_REQUEST_EVENT_TYPE != 'merge_train'
    # merge trains
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' &&
        $CI_MERGE_REQUEST_EVENT_TYPE == 'merge_train'
    # tip of the default branch
    - if: $CI_PIPELINE_SOURCE == 'web' &&
        $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == 'push' &&
        $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    # scheduled pipelines
    - if: $CI_PIPELINE_SOURCE == 'schedule'

stages:
  - test
  - external
  - deploy

default:
  image: quay.io/hummingbird-ci/gitlab-ci:latest
  tags: [small-runner]
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - unknown_failure
      - api_failure
      - job_execution_timeout

.rules:
  mr:
    if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  push:
    if: $CI_PIPELINE_SOURCE == 'push' && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  web:
    if: $CI_PIPELINE_SOURCE == 'web' && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  schedule:
    if: $CI_PIPELINE_SOURCE == 'schedule' && $CI_JOB_NAME == $ONLY_JOB_NAME
  mr_manual:
    if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    when: manual
    allow_failure: true # allow to merge MR without running this job

tree_status:
  stage: external
  script:
    - make generate-host
    - ./ci/tree_status.sh
  rules:
    - !reference [.rules, mr]
    - !reference [.rules, push]

check:
  script:
    - make check-host
  rules:
    - !reference [.rules, mr]

deploy_components_to_konflux:
  variables:
    PARENT_PROJECT_PATH: $CI_PROJECT_PATH
    PARENT_MERGE_REQUEST_IID: $CI_MERGE_REQUEST_IID
    PARENT_COMMIT_SHA: $CI_COMMIT_SHA
    ONLY_JOB_NAME: rpms-components
  trigger:
    project: redhat/hummingbird/infrastructure
    strategy: depend
  allow_failure: true
  when: manual
  rules:
    - !reference [.rules, mr]
    - !reference [.rules, push]
    - !reference [.rules, web]

dist_git_update:
  environment:
    name: chore-mr
    action: access
  allow_failure: true
  when: manual
  before_script:
    - |
      git config --local user.name "${GITLAB_USER_NAME}"
      git config --local user.email "${GITLAB_USER_EMAIL}"
      git fetch --quiet origin
      git remote set-url origin "https://${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
      git config --local credential.username ignored
      git config --local credential.helper "!echo \"password=\$CHORE_MR_GITLAB_TOKEN\"; :"
      git branch --quiet --force "${CI_COMMIT_BRANCH:-$CI_DEFAULT_BRANCH}" "origin/${CI_COMMIT_BRANCH:-$CI_DEFAULT_BRANCH}"
  script:
    - |
      ./ci/dist_git.py update
      ./ci/create_mr.sh --branch chore/dist-git-update --title "chore(rpms): Update dist-git packages"
  rules:
    - !reference [.rules, mr]
    - !reference [.rules, schedule]
    - !reference [.rules, web]

trigger_documentation:
  stage: deploy
  needs: [{job: deploy_hugo_tag, optional: true}]
  variables:
    PARENT_PROJECT_PATH: $CI_PROJECT_PATH
  trigger:
    project: redhat/hummingbird/documentation
    strategy: depend
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE =~ 'push|web' && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - documentation/**/*
        - README.md
        - CONTRIBUTING.md
    - !reference [.rules, mr_manual]
