#!/bin/bash

if [ -d /tmp/test-ttmkfdir ];then
	rm -rf /tmp/test-ttmkfdir
fi

mkdir /tmp/test-ttmkfdir
cd /tmp/test-ttmkfdir
ttmkfdir -d /usr/share/fonts/sazanami/gothic .
if [ -f ./fonts.scale ]; then
	diff -urN ./fonts.scale /usr/share/fonts/sazanami/gothic/fonts.scale
	retval=$?
	echo $retval
	if [ $retval -ne 0 ]; then
		echo "check if sazanami-gothic-fonts is installed or its packaging is changed"
		exit 1
	else
		echo "ttmkfdir sucessfully generated fonts.scale file for sazanami-gothic-fonts directory"
	fi
fi


