#!/bin/bash

# Usage:
#     ./update-release runtime-version|latest-release|latest-commit [--bug bug-id] [--tarball tarball-name] [--release-json release-json] [--larger-rpm-release]

set -euo pipefail
IFS=$'\n\t'
set -x

print_usage() {
    echo " Usage:"
    echo "     ./update-release runtime-version|latest-release|latest-commit [--bootstrap] [--bug bug-id] [--tarball tarball-name] [--release-json release-json] [--larger-rpm-release]"
    echo ""
    echo "The runtime-version parameter needs to match the github release name."
    echo "For preview releases, runtime-version should be of the form '9.0 Preview 1'."
}

download_release_json() {
    version=$1
    cat > query <<'EOF'
    [ .[] | select(.name | test("\\.NET .*\($v)\\.1\\d{2}")) | select(.author.login | contains("dotnet-sb-bot")) ]
    | first
    | { tag_name: .tag_name,
        tarball: .tarball_url,
        signature: .assets[].browser_download_url | select(. | endswith("tar.gz.sig")),
        release_manifest: .assets[] | select(.name == "release.json") | .browser_download_url }
EOF
    curl https://api.github.com/repos/dotnet/dotnet/releases \
        | jq --arg v $dotnet_major_minor_version --from-file query > release.metadata.github
    curl -L "$(jq -r .release_manifest release.metadata.github)" -o release.json
}

user_provided_tarball_name=""

rpm_release=1
positional_args=()
bug_ids=()
bootstrap=0
while [[ "$#" -gt 0 ]]; do
    arg="$1"
    case "${arg}" in
        --bootstrap)
            bootstrap=1
            shift;
            ;;
        --bug)
            bug_ids+=("$2")
            shift;
            shift;
            ;;
        -h|--help)
            print_usage
            exit 0
            ;;
        --release-json)
            release_json="$2"
            shift;
            shift;
            ;;
        --tarball)
            user_provided_tarball_name="$2"
            shift;
            shift;
            ;;
        --larger-rpm-release)
            rpm_release="2"
            shift;
            ;;
        *)
            positional_args+=("$1")
            shift
            ;;
    esac
done

spec_files=( ./*.spec )
spec_file="${spec_files[0]}"

dotnet_major_minor_version=$spec_file
dotnet_major_minor_version=${dotnet_major_minor_version#./dotnet}
dotnet_major_minor_version=${dotnet_major_minor_version%.spec}

echo "Updating .NET $dotnet_major_minor_version"

runtime_version=${positional_args[0]:-latest-release}
sdk_version=""
tag=v${runtime_version}
created_release_json=0

if [[ ${runtime_version} == latest-release ]]; then
    if [[ -n "${release_json:-}" ]]; then
        cp -a "${release_json}" release.json
    else
        download_release_json "${dotnet_major_minor_version}"
    fi
elif [[ ${runtime_version} == latest-commit ]]; then
    cat > query <<EOF
    [ .[] | select(.name == "main") ]
    | first
EOF
    curl https://api.github.com/repos/dotnet/dotnet/branches \
        | jq --from-file query > release.metadata.github
    commit=$(jq -r .commit.sha release.metadata.github)
    jq >release.json <<EOF
{
      "release": "$dotnet_major_minor_version",
      "channel": "$dotnet_major_minor_version",
      "tag": "$commit",
      "sdkVersion": "$dotnet_major_minor_version",
      "runtimeVersion": "$dotnet_major_minor_version",
      "aspNetCoreVersion": "$dotnet_major_minor_version",
      "sourceRepository": "https://github.com/dotnet/dotnet",
      "sourceVersion": "$commit"
}
EOF
    cat release.json
    created_release_json=1
else
    if [[ -n "${release_json:-}" ]]; then
        cp -a "${release_json}" release.json
    else
        download_release_json "${runtime_version}"
    fi
fi

cat release.json

aspnetcore_runtime_version=$(jq -r .aspNetCoreVersion release.json)
runtime_version=$(jq -r .runtimeVersion release.json)
sdk_version=$(jq -r .sdkVersion release.json)
tag=$(jq -r .tag release.json)
tag_without_v=$(echo ${tag} | sed -e 's|^v||')

echo "Updating .NET $dotnet_major_minor_version to SDK ${sdk_version} and Runtime ${runtime_version}"

if [[ $bootstrap == 0 ]]; then
    sed -i -E "s|^%bcond_with.*bootstrap$|%bcond_with bootstrap|" "$spec_file"
else
    sed -i -E "s|^%bcond_with.*bootstrap$|%bcond_without bootstrap|" "$spec_file"
fi

sed -i -E "s|^%global upstream_tag .*$|%global upstream_tag ${tag}|" "$spec_file"

sed -i -E "s|^%global runtime_version .*$|%global runtime_version ${runtime_version}|" "$spec_file"
sed -i -E "s|^%global aspnetcore_runtime_version .*$|%global aspnetcore_runtime_version ${aspnetcore_runtime_version}|" "$spec_file"
sed -i -E "s|^%global sdk_version .*$|%global sdk_version ${sdk_version}|" "$spec_file"

if [[ $runtime_version = *preview* ]] || [[ $runtime_version = *rc* ]]; then
    # For Preview/RC releases, convert x.y.z-preview.a.b to x.y.z~preview.a.b (replace - with ~)
    # https://docs.fedoraproject.org/en-US/packaging-guidelines/Versioning/#_handling_non_sorting_versions_with_tilde_dot_and_caret
    runtime_rpm_version=${runtime_version/-/\~}
    aspnetcore_runtime_rpm_version=${aspnetcore_runtime_version/-/\~}
    sdk_rpm_version=${sdk_version/-/\~}
    sed -i -E "s|^(%global runtime_rpm_version) .*$|\1 ${runtime_rpm_version}|" "$spec_file"
    sed -i -E "s|^(%global aspnetcore_runtime_rpm_version) .*$|\1 ${aspnetcore_runtime_rpm_version}|" "$spec_file"
    sed -i -E "s|^(%global sdk_rpm_version) .*$|\1 ${sdk_rpm_version}|" "$spec_file"
else
    # For GA releases replace rpm versions with rpm macros for the actual version
    sed -i -E "s|^(%global runtime_rpm_version) .*$|\1 %{runtime_version}|" "$spec_file"
    sed -i -E "s|^(%global aspnetcore_runtime_rpm_version) .*$|\1 %{aspnetcore_runtime_version}|" "$spec_file"
    sed -i -E "s|^(%global sdk_rpm_version) .*$|\1 %{sdk_version}|" "$spec_file"
fi

if [[ -f "dotnet-${tag_without_v}.tar.gz" ]]; then
    echo "dotnet-${tag_without_v}.tar.gz already exists, not rebuilding tarball"
elif [[ -n ${user_provided_tarball_name} ]]; then
    cp -a "${user_provided_tarball_name}" "dotnet-${tag_without_v}.tar.gz"
    cp -a "${user_provided_tarball_name}.sig" "dotnet-${tag_without_v}.tar.gz.sig"
else
    if [[ $created_release_json == 0 ]] then
        rm -f release.json
    fi
    spectool -g "$spec_file"
fi

if [[ $bootstrap == 1 ]]; then
    tar xf "dotnet-${tag_without_v}.tar.gz" "dotnet-${tag_without_v}/global.json"
    bootstrap_sdk_version=$(jq -r .tools.dotnet "dotnet-${tag_without_v}/global.json")
    sed -i -E "s|^(%global bootstrap_sdk_version) .*$|\1 ${bootstrap_sdk_version}|" "$spec_file"

    ./build-dotnet-bootstrap-tarball "${tag_without_v}"

    if [ -f dotnet-prebuilts*ppc64le*tar.gz ]; then
        file_name=$(ls -1 -t dotnet-prebuilts-*-ppc64le.tar.gz | head -1)
        bootstrap_sdk_version_ppc64le_s390x=$(basename $file_name | sed -E -e 's/dotnet-prebuilts-//' -e 's/-ppc64le.tar.gz//')

        sed -E -i "s|^%global bootstrap_sdk_version_ppc64le_s390x .*$|%global bootstrap_sdk_version_ppc64le_s390x $bootstrap_sdk_version_ppc64le_s390x|" "$spec_file"
    fi
fi

set -x

comment="Update to .NET SDK ${sdk_version} and Runtime ${runtime_version}"
commit_message="$comment
"
for bug_id in "${bug_ids[@]}"; do
    if [[ "$bug_id" =~ ^[[:digit:]]+$ ]]; then
        comment="$comment
- Resolves: RHBZ#$bug_id"
        commit_message="$commit_message
Resolves: RHBZ#$bug_id"
    else
        comment="$comment
- Resolves: $bug_id"
        commit_message="$commit_message
Resolves: $bug_id"
    fi
done

echo "$commit_message" > git-commit-message

rpmdev-bumpspec --comment="$comment" "$spec_file"

# Reset release in 'Release' tag
sed -i -E 's|^Release:        [[:digit:]]+%|Release:        '"$rpm_release"'%|' "$spec_file"
# Reset Release in changelog comment
# See https://stackoverflow.com/questions/18620153/find-matching-text-and-replace-next-line
sed -i -E '/^%changelog$/!b;n;s/-[[:digit:]]+$/-'"$rpm_release"'/' "$spec_file"
