upstream_project_url: https://github.com/jlebon/chunkah
upstream_tag_template: v{version}
issue_repository: https://github.com/jlebon/chunkah

jobs:
  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-all

  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      - fedora-branched
