---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://gitlab.com/redhat/hummingbird/rpms/-/tree/{{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-path-change: "[rpms/rootfiles/***]"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: rpms-main
    appstudio.openshift.io/component: rootfiles-main
    pipelines.appstudio.openshift.io/type: build
  name: rootfiles-main-on-pull-request
  namespace: hummingbird-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: image-expires-after
      value: 5d
    - name: ociStorage
      value: quay.io/redhat-user-workloads/hummingbird-tenant/rootfiles-main:on-mr-{{pull_request_number}}-{{revision}}
    - name: package-name
      value: rootfiles
    - name: target-branch
      value: '{{target_branch}}'
    - name: path-context
      value: "rpms/rootfiles"
    - name: self-ref-url
      value: "https://github.com/scoheb/rpmbuild-pipeline.git"
    - name: self-ref-revision
      value: "add-pulp-support"
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/scoheb/rpmbuild-pipeline.git"
      - name: revision
        value: "add-pulp-support"
      - name: pathInRepo
        value: "pipeline/hummingbird-build-rpm-package.yaml"
  taskRunTemplate:
    serviceAccountName: build-pipeline-rootfiles-main
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{git_auth_secret}}'
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://gitlab.com/redhat/hummingbird/rpms/-/tree/{{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-path-change: "[rpms/setup/***]"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: rpms-main
    appstudio.openshift.io/component: setup-main
    pipelines.appstudio.openshift.io/type: build
  name: setup-main-on-pull-request
  namespace: hummingbird-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: image-expires-after
      value: 5d
    - name: ociStorage
      value: quay.io/redhat-user-workloads/hummingbird-tenant/setup-main:on-mr-{{pull_request_number}}-{{revision}}
    - name: package-name
      value: setup
    - name: target-branch
      value: '{{target_branch}}'
    - name: path-context
      value: "rpms/setup"
    - name: self-ref-url
      value: "https://github.com/scoheb/rpmbuild-pipeline.git"
    - name: self-ref-revision
      value: "add-pulp-support"
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/scoheb/rpmbuild-pipeline.git"
      - name: revision
        value: "add-pulp-support"
      - name: pathInRepo
        value: "pipeline/hummingbird-build-rpm-package.yaml"
  taskRunTemplate:
    serviceAccountName: build-pipeline-setup-main
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{git_auth_secret}}'
