---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://gitlab.com/redhat/hummingbird/rpms/-/tree/{{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-path-change: "[rpms/bash/***, mock/mock.cfg, test/rpms/bash.yml]"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: rpms-main
    appstudio.openshift.io/component: bash-main
    pipelines.appstudio.openshift.io/type: build
  name: bash-main-on-pull-request
  namespace: hummingbird-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: image-expires-after
      value: 5d
    - name: ociStorage
      value: quay.io/redhat-user-workloads/hummingbird-tenant/bash-main:on-mr-{{pull_request_number}}-{{revision}}
    - name: package-name
      value: bash
    - name: target-branch
      value: '{{target_branch}}'
    - name: build-architectures
      value:
        - aarch64
        - x86_64
    - name: specfile
      value: "bash.spec"
    - name: monorepo-subdir
      value: "rpms/bash"
    - name: mock-config-template-file
      value: "mock/mock.cfg"
    - name: self-ref-url
      value: "https://github.com/konflux-ci/rpmbuild-pipeline.git"
    - name: self-ref-revision
      value: "ada7af0e5397443d320e4273ebe157df21fa1547"
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/konflux-ci/rpmbuild-pipeline.git"
      - name: revision
        value: "ada7af0e5397443d320e4273ebe157df21fa1547"
      - name: pathInRepo
        value: "pipeline/build-rpm-package.yaml"
  taskRunTemplate:
    serviceAccountName: build-pipeline-bash-main
  timeouts:
    pipeline: 12h
    tasks: 12h
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{git_auth_secret}}'
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://gitlab.com/redhat/hummingbird/rpms/-/tree/{{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-path-change: "[rpms/curl/***, mock/mock.cfg]"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: rpms-main
    appstudio.openshift.io/component: curl-main
    pipelines.appstudio.openshift.io/type: build
  name: curl-main-on-pull-request
  namespace: hummingbird-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: image-expires-after
      value: 5d
    - name: ociStorage
      value: quay.io/redhat-user-workloads/hummingbird-tenant/curl-main:on-mr-{{pull_request_number}}-{{revision}}
    - name: package-name
      value: curl
    - name: target-branch
      value: '{{target_branch}}'
    - name: build-architectures
      value:
        - aarch64
        - x86_64
    - name: specfile
      value: "curl.spec"
    - name: monorepo-subdir
      value: "rpms/curl"
    - name: mock-config-template-file
      value: "mock/mock.cfg"
    - name: self-ref-url
      value: "https://github.com/konflux-ci/rpmbuild-pipeline.git"
    - name: self-ref-revision
      value: "ada7af0e5397443d320e4273ebe157df21fa1547"
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/konflux-ci/rpmbuild-pipeline.git"
      - name: revision
        value: "ada7af0e5397443d320e4273ebe157df21fa1547"
      - name: pathInRepo
        value: "pipeline/build-rpm-package.yaml"
  taskRunTemplate:
    serviceAccountName: build-pipeline-curl-main
  timeouts:
    pipeline: 12h
    tasks: 12h
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{git_auth_secret}}'
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://gitlab.com/redhat/hummingbird/rpms/-/tree/{{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-path-change: "[rpms/grep/***, mock/mock.cfg]"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: rpms-main
    appstudio.openshift.io/component: grep-main
    pipelines.appstudio.openshift.io/type: build
  name: grep-main-on-pull-request
  namespace: hummingbird-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: image-expires-after
      value: 5d
    - name: ociStorage
      value: quay.io/redhat-user-workloads/hummingbird-tenant/grep-main:on-mr-{{pull_request_number}}-{{revision}}
    - name: package-name
      value: grep
    - name: target-branch
      value: '{{target_branch}}'
    - name: build-architectures
      value:
        - aarch64
        - x86_64
    - name: specfile
      value: "grep.spec"
    - name: monorepo-subdir
      value: "rpms/grep"
    - name: mock-config-template-file
      value: "mock/mock.cfg"
    - name: self-ref-url
      value: "https://github.com/konflux-ci/rpmbuild-pipeline.git"
    - name: self-ref-revision
      value: "ada7af0e5397443d320e4273ebe157df21fa1547"
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/konflux-ci/rpmbuild-pipeline.git"
      - name: revision
        value: "ada7af0e5397443d320e4273ebe157df21fa1547"
      - name: pathInRepo
        value: "pipeline/build-rpm-package.yaml"
  taskRunTemplate:
    serviceAccountName: build-pipeline-grep-main
  timeouts:
    pipeline: 12h
    tasks: 12h
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{git_auth_secret}}'
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://gitlab.com/redhat/hummingbird/rpms/-/tree/{{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-path-change: "[rpms/hostname/***, mock/mock.cfg, test/rpms/hostname.yml]"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: rpms-main
    appstudio.openshift.io/component: hostname-main
    pipelines.appstudio.openshift.io/type: build
  name: hostname-main-on-pull-request
  namespace: hummingbird-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: image-expires-after
      value: 5d
    - name: ociStorage
      value: quay.io/redhat-user-workloads/hummingbird-tenant/hostname-main:on-mr-{{pull_request_number}}-{{revision}}
    - name: package-name
      value: hostname
    - name: target-branch
      value: '{{target_branch}}'
    - name: build-architectures
      value:
        - aarch64
        - x86_64
    - name: specfile
      value: "hostname.spec"
    - name: monorepo-subdir
      value: "rpms/hostname"
    - name: mock-config-template-file
      value: "mock/mock.cfg"
    - name: self-ref-url
      value: "https://github.com/konflux-ci/rpmbuild-pipeline.git"
    - name: self-ref-revision
      value: "ada7af0e5397443d320e4273ebe157df21fa1547"
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/konflux-ci/rpmbuild-pipeline.git"
      - name: revision
        value: "ada7af0e5397443d320e4273ebe157df21fa1547"
      - name: pathInRepo
        value: "pipeline/build-rpm-package.yaml"
  taskRunTemplate:
    serviceAccountName: build-pipeline-hostname-main
  timeouts:
    pipeline: 12h
    tasks: 12h
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{git_auth_secret}}'
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://gitlab.com/redhat/hummingbird/rpms/-/tree/{{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-path-change: "[rpms/rootfiles/***, mock/mock.cfg, test/rpms/rootfiles.yml]"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: rpms-main
    appstudio.openshift.io/component: rootfiles-main
    pipelines.appstudio.openshift.io/type: build
  name: rootfiles-main-on-pull-request
  namespace: hummingbird-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: image-expires-after
      value: 5d
    - name: ociStorage
      value: quay.io/redhat-user-workloads/hummingbird-tenant/rootfiles-main:on-mr-{{pull_request_number}}-{{revision}}
    - name: package-name
      value: rootfiles
    - name: target-branch
      value: '{{target_branch}}'
    - name: build-architectures
      value:
        - aarch64
        - x86_64
    - name: specfile
      value: "rootfiles.spec"
    - name: monorepo-subdir
      value: "rpms/rootfiles"
    - name: mock-config-template-file
      value: "mock/mock.cfg"
    - name: self-ref-url
      value: "https://github.com/konflux-ci/rpmbuild-pipeline.git"
    - name: self-ref-revision
      value: "ada7af0e5397443d320e4273ebe157df21fa1547"
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/konflux-ci/rpmbuild-pipeline.git"
      - name: revision
        value: "ada7af0e5397443d320e4273ebe157df21fa1547"
      - name: pathInRepo
        value: "pipeline/build-rpm-package.yaml"
  taskRunTemplate:
    serviceAccountName: build-pipeline-rootfiles-main
  timeouts:
    pipeline: 12h
    tasks: 12h
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{git_auth_secret}}'
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://gitlab.com/redhat/hummingbird/rpms/-/tree/{{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-path-change: "[rpms/rpm/***, mock/mock.cfg, test/rpms/rpm.yml]"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: rpms-main
    appstudio.openshift.io/component: rpm-main
    pipelines.appstudio.openshift.io/type: build
  name: rpm-main-on-pull-request
  namespace: hummingbird-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: image-expires-after
      value: 5d
    - name: ociStorage
      value: quay.io/redhat-user-workloads/hummingbird-tenant/rpm-main:on-mr-{{pull_request_number}}-{{revision}}
    - name: package-name
      value: rpm
    - name: target-branch
      value: '{{target_branch}}'
    - name: build-architectures
      value:
        - aarch64
        - x86_64
    - name: specfile
      value: "rpm.spec"
    - name: monorepo-subdir
      value: "rpms/rpm"
    - name: mock-config-template-file
      value: "mock/mock.cfg"
    - name: self-ref-url
      value: "https://github.com/konflux-ci/rpmbuild-pipeline.git"
    - name: self-ref-revision
      value: "ada7af0e5397443d320e4273ebe157df21fa1547"
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/konflux-ci/rpmbuild-pipeline.git"
      - name: revision
        value: "ada7af0e5397443d320e4273ebe157df21fa1547"
      - name: pathInRepo
        value: "pipeline/build-rpm-package.yaml"
  taskRunTemplate:
    serviceAccountName: build-pipeline-rpm-main
  timeouts:
    pipeline: 12h
    tasks: 12h
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{git_auth_secret}}'
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://gitlab.com/redhat/hummingbird/rpms/-/tree/{{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-path-change: "[rpms/setup/***, mock/mock.cfg, test/rpms/setup.yml]"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: rpms-main
    appstudio.openshift.io/component: setup-main
    pipelines.appstudio.openshift.io/type: build
  name: setup-main-on-pull-request
  namespace: hummingbird-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: image-expires-after
      value: 5d
    - name: ociStorage
      value: quay.io/redhat-user-workloads/hummingbird-tenant/setup-main:on-mr-{{pull_request_number}}-{{revision}}
    - name: package-name
      value: setup
    - name: target-branch
      value: '{{target_branch}}'
    - name: build-architectures
      value:
        - aarch64
        - x86_64
    - name: specfile
      value: "setup.spec"
    - name: monorepo-subdir
      value: "rpms/setup"
    - name: mock-config-template-file
      value: "mock/mock.cfg"
    - name: self-ref-url
      value: "https://github.com/konflux-ci/rpmbuild-pipeline.git"
    - name: self-ref-revision
      value: "ada7af0e5397443d320e4273ebe157df21fa1547"
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/konflux-ci/rpmbuild-pipeline.git"
      - name: revision
        value: "ada7af0e5397443d320e4273ebe157df21fa1547"
      - name: pathInRepo
        value: "pipeline/build-rpm-package.yaml"
  taskRunTemplate:
    serviceAccountName: build-pipeline-setup-main
  timeouts:
    pipeline: 12h
    tasks: 12h
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{git_auth_secret}}'
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://gitlab.com/redhat/hummingbird/rpms/-/tree/{{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-path-change: "[rpms/systemd-stub/***, mock/mock.cfg]"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: rpms-main
    appstudio.openshift.io/component: systemd-stub-main
    pipelines.appstudio.openshift.io/type: build
  name: systemd-stub-main-on-pull-request
  namespace: hummingbird-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: image-expires-after
      value: 5d
    - name: ociStorage
      value: quay.io/redhat-user-workloads/hummingbird-tenant/systemd-stub-main:on-mr-{{pull_request_number}}-{{revision}}
    - name: package-name
      value: systemd-stub
    - name: target-branch
      value: '{{target_branch}}'
    - name: build-architectures
      value:
        - aarch64
        - x86_64
    - name: specfile
      value: "systemd-stub.spec"
    - name: monorepo-subdir
      value: "rpms/systemd-stub"
    - name: mock-config-template-file
      value: "mock/mock.cfg"
    - name: self-ref-url
      value: "https://github.com/konflux-ci/rpmbuild-pipeline.git"
    - name: self-ref-revision
      value: "ada7af0e5397443d320e4273ebe157df21fa1547"
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/konflux-ci/rpmbuild-pipeline.git"
      - name: revision
        value: "ada7af0e5397443d320e4273ebe157df21fa1547"
      - name: pathInRepo
        value: "pipeline/build-rpm-package.yaml"
  taskRunTemplate:
    serviceAccountName: build-pipeline-systemd-stub-main
  timeouts:
    pipeline: 12h
    tasks: 12h
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{git_auth_secret}}'
