---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://gitlab.com/redhat/hummingbird/rpms/-/tree/{{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-path-change: "[rpms/hostname/***]"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: rpms-main
    appstudio.openshift.io/component: hostname-main
    pipelines.appstudio.openshift.io/type: build
  name: hostname-main-on-push
  namespace: hummingbird-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: ociStorage
      value: quay.io/redhat-user-workloads/hummingbird-tenant/hostname-main:{{revision}}
    - name: package-name
      value: hostname
    - name: target-branch
      value: '{{target_branch}}'
    - name: build-architectures
      value:
        - aarch64
        - x86_64
    - name: specfile
      value: "hostname.spec"
    - name: monorepo-subdir
      value: "rpms/hostname"
    - name: mock-config-template-file
      value: "mock/mock.cfg"
    - name: self-ref-url
      value: "https://github.com/scoheb/rpmbuild-pipeline.git"
    - name: self-ref-revision
      value: "mock-config-from-source"
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/scoheb/rpmbuild-pipeline.git"
      - name: revision
        value: "mock-config-from-source"
      - name: pathInRepo
        value: "pipeline/build-rpm-package.yaml"
  taskRunTemplate:
    serviceAccountName: build-pipeline-hostname-main
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{git_auth_secret}}'
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://gitlab.com/redhat/hummingbird/rpms/-/tree/{{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-path-change: "[rpms/rootfiles/***]"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: rpms-main
    appstudio.openshift.io/component: rootfiles-main
    pipelines.appstudio.openshift.io/type: build
  name: rootfiles-main-on-push
  namespace: hummingbird-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: ociStorage
      value: quay.io/redhat-user-workloads/hummingbird-tenant/rootfiles-main:{{revision}}
    - name: package-name
      value: rootfiles
    - name: target-branch
      value: '{{target_branch}}'
    - name: build-architectures
      value:
        - aarch64
        - x86_64
    - name: specfile
      value: "rootfiles.spec"
    - name: monorepo-subdir
      value: "rpms/rootfiles"
    - name: mock-config-template-file
      value: "mock/mock.cfg"
    - name: self-ref-url
      value: "https://github.com/scoheb/rpmbuild-pipeline.git"
    - name: self-ref-revision
      value: "mock-config-from-source"
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/scoheb/rpmbuild-pipeline.git"
      - name: revision
        value: "mock-config-from-source"
      - name: pathInRepo
        value: "pipeline/build-rpm-package.yaml"
  taskRunTemplate:
    serviceAccountName: build-pipeline-rootfiles-main
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{git_auth_secret}}'
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://gitlab.com/redhat/hummingbird/rpms/-/tree/{{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-path-change: "[rpms/rpm/***]"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: rpms-main
    appstudio.openshift.io/component: rpm-main
    pipelines.appstudio.openshift.io/type: build
  name: rpm-main-on-push
  namespace: hummingbird-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: ociStorage
      value: quay.io/redhat-user-workloads/hummingbird-tenant/rpm-main:{{revision}}
    - name: package-name
      value: rpm
    - name: target-branch
      value: '{{target_branch}}'
    - name: build-architectures
      value:
        - aarch64
        - x86_64
    - name: specfile
      value: "rpm.spec"
    - name: monorepo-subdir
      value: "rpms/rpm"
    - name: mock-config-template-file
      value: "mock/mock.cfg"
    - name: self-ref-url
      value: "https://github.com/scoheb/rpmbuild-pipeline.git"
    - name: self-ref-revision
      value: "mock-config-from-source"
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/scoheb/rpmbuild-pipeline.git"
      - name: revision
        value: "mock-config-from-source"
      - name: pathInRepo
        value: "pipeline/build-rpm-package.yaml"
  taskRunTemplate:
    serviceAccountName: build-pipeline-rpm-main
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{git_auth_secret}}'
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://gitlab.com/redhat/hummingbird/rpms/-/tree/{{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-path-change: "[rpms/setup/***]"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: rpms-main
    appstudio.openshift.io/component: setup-main
    pipelines.appstudio.openshift.io/type: build
  name: setup-main-on-push
  namespace: hummingbird-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: ociStorage
      value: quay.io/redhat-user-workloads/hummingbird-tenant/setup-main:{{revision}}
    - name: package-name
      value: setup
    - name: target-branch
      value: '{{target_branch}}'
    - name: build-architectures
      value:
        - aarch64
        - x86_64
    - name: specfile
      value: "setup.spec"
    - name: monorepo-subdir
      value: "rpms/setup"
    - name: mock-config-template-file
      value: "mock/mock.cfg"
    - name: self-ref-url
      value: "https://github.com/scoheb/rpmbuild-pipeline.git"
    - name: self-ref-revision
      value: "mock-config-from-source"
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/scoheb/rpmbuild-pipeline.git"
      - name: revision
        value: "mock-config-from-source"
      - name: pathInRepo
        value: "pipeline/build-rpm-package.yaml"
  taskRunTemplate:
    serviceAccountName: build-pipeline-setup-main
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{git_auth_secret}}'
