[tox]
env_list =
    formatters
    lint
    typing-py{36,39,311,312}

[testenv:formatters]
description = Run formatters
skip_install = true
deps =
    isort
    black
commands =
    black {posargs} ansible_collection.py ansible-generator
    isort {posargs} ansible_collection.py ansible-generator

[testenv:lint]
description = Run linters
skip_install = true
deps =
    ruff
commands =
    ruff check {posargs} ansible_collection.py ansible-generator

[testenv:typing-py{36,39,311,312}]
description = Run type checkers
skip_install = true
deps =
    mypy
    types-pyyaml
commands =
    mypy {posargs} ansible_collection.py ansible-generator
set_env =
    PYTHONPATH=${PWD}
